### ISSUE TITLE
Sign-up (Sprint 09/29/21)

### ISSUE THREAD

**Issue by braydenflaig** [COSC481W-2021Fall/capstone-thriving-5#7]
In order to have consistency in my information, as a college student, I want to be able to create an account that can save my information and allow me to sign in next time. 
Acceptance Criteria:
 1. Be able to store multiple users 
 2. Not allow multiple users to have the same username
 3. Accurately store the user information
 4. Throws an error if the user doesn't enter in any of the boxes all are required
 5. After finishing signing up the user will be directed to the home page. 
 6. The password should be encrypted/hashed in the database for security
 
Task List:
- [x]  on the back end, setup database scheme (Brayden)

- [ ] on the back end, encrypt/hash password

- [x]  on the back end, check for the same usernames (Chris)

- [x]  front end, need 5 textboxes, and a button (Fentry)

- [x]  front end, need a basic homepage to direct the user to (Stephen)

- [x]  front end, throw a warning for empty text boxes when attempting to sign up. (Janelle)

**Comment by sjiang1** [comment]
Just thought about one extra acceptance criterion:
The password should have a minimum requirement, such as minimum length, etc.
